[font]
size = 12
normal = { family = "RobotoMono Nerd Font", style = "Regular" }
bold = { family = "RobotoMono Nerd Font", style = "Bold" }
italic = { family = "RobotoMono Nerd Font", style = "Italic" }

[colors.primary]
background = '#001a1d'
foreground = '#839496'

[colors.normal]
black   = '#073642'
red     = '#dc322f'
green   = '#859900'
yellow  = '#b58900'
blue    = '#268bd2'
magenta = '#d33682'
cyan    = '#2aa198'
white   = '#eee8d5'

[colors.bright]
black   = '#4c4c4c'
red     = '#cb4b16'
green   = '#586e75'
yellow  = '#657b83'
blue    = '#839496'
magenta = '#6c71c4'
cyan    = '#93a1a1'
white   = '#fdf6e3'

